### ISSUE TITLE
Add hlig + Character variant

### ISSUE THREAD

**Issue by dhinostroza** [RolandDreger/open-type-features#3]
Hi, Roland:
This can be very useful for me with a couple of additions. Namely, I need to be able to combine hlig (historical ligatures) + Character variant 83 2 and hlig + Character variant 84 2. Could you please add them to your script?
I can add Spanish to the dialogs (English, German, French), if you consider it useful.
Best regards,
Daniel

**Comment by RolandDreger** [comment]
Hi Daniel,

I'm actually planning a new version of the script that will allow you to assign various OpenType features that are not available through InDesign's UI – including hlig and Character Variants.

Since these are not accessible via the UI, would it be helpful to mark the affected text passages? Do you assign them to the whole text or only to some selected characters?

<img width="976" alt="mark_otf" src="https://user-images.githubusercontent.com/19747449/147224336-4055af04-052f-4cfa-b121-b6aedaf84c0d.png">


> I can add Spanish to the dialogs (English, German, French), if you consider it useful.

Yes, for sure. That would be helpful. I will add the machine translated texts for Spanish in the next version. If you then take a look at it, that would be great. 

Roland

**Comment by dhinostroza** [comment]
Hi, Roland:
Thank you. These are very specific variants for a particular font (Junicode Two Beta) and combination of letters.
**1. hlig + character-variant cv83 2:** The combination of  q́ꝫ  produces:
![Screen Shot 2021-12-23 at 09 26 20](https://user-images.githubusercontent.com/18691188/147253821-74d0b6df-586f-4543-aa87-eadd822428c9.png)

**2. hlig + character-variant cv84 2:** This modifies accents in vowels, creating a half-macron + half breve: 
![Screen Shot 2021-12-23 at 09 30 15](https://user-images.githubusercontent.com/18691188/147254190-02343b40-0023-4518-ba8b-db4ce6c6b8fd.png)

Regarding Spanish, great! Let me know when you're ready.
Best,
Daniel

**Comment by RolandDreger** [comment]
Hi Daniel,

do you want to make a first test run with the script? You can find the new version in the branch "Develop" and I also attach it here:

[openTypeFeatures.zip](https://github.com/RolandDreger/open-type-features/files/7884942/openTypeFeatures.zip)

## Extended Tab
There are now two new tabs. If you click on »Extended features/Funcionalidad extendida« you can apply all kind of OpenType features.

<img width="808" alt="new_extended_tab" src="https://user-images.githubusercontent.com/19747449/149843809-e0fff32f-8264-4431-802b-223d62d7ba4d.png">

In the lower part of the tab is a filter to limit the features. Multiple tags are separated by spaces, so in your case `hlig cv84`.

<img width="762" alt="feature_filter" src="https://user-images.githubusercontent.com/19747449/149844043-070dec46-6789-49e8-a970-defa326f00b8.png">

By double-clicking on the entry in the list you can change the value, e.g. from `1` to `2`.

## Assign the value
Select the desired text. Then mark one or more features in the list on the left and click on the button »Assign/Aplique«.

## Remove features
With the button »Clear/Borrar« the features can be removed from the selected text.

If you have any questions, please just let me know.

## Translation
If you notice any wrong or weird translations, feel free to correct them directly in the script. (They are at the very end of the script code, starting at line 5141) and reattach the corrected version here. Or alternatively, fix it directly via Github or let me know about. Thanks!

Roland

**Comment by dhinostroza** [comment]
Hi, Roland
Sorry for not replying sooner. I tried the new script but it didn't apply the combination of hlig + cv84 2.
Very kind regards,
Daniel

**Comment by RolandDreger** [comment]
Hi Daniel, 

what exactly is not working? Can you describe the issue in more detail? Is there no assignment of these features to the corresponding text? Or does the font not show the desired change after the assignment?

Can you post a screenshot here after applying it through the script?

I tested it with the font Junicode Two Beta, here is my result:

<img width="1239" alt="hlig_cv84" src="https://user-images.githubusercontent.com/19747449/154142796-32f37896-82d0-4a34-9da9-9c5a35e1e2a8.png">


Roland

**Comment by dhinostroza** [comment]
Hi, Roland:
I didn't have the time to test it thoroughly before but now I made it work for (two characters with) hlig + cv84 2!
Here are the screenshots:
Before:
![before hlig cv84 2](https://user-images.githubusercontent.com/18691188/155738576-889619a7-6ba0-496b-bf7f-09984f4cf9b0.png)

After:
![after hlig cv84 2](https://user-images.githubusercontent.com/18691188/155738588-1f332f2e-54ca-43d3-bb30-758203a71837.png)

I'll post another for (three characters with) hlig + cv83 2, as this is still giving me problems.
All the very best,
Daniel

**Comment by dhinostroza** [comment]
The tricky part is combining three characters with hlig + cv83 2.
This is what the CSS + HTML code looks like for the characters  q + accent + ꝫ (& #113;& #769;& #42859; without the spaces):

  .character-variant83 {
  font-family: 'JunicodeTwoBeta-Regular';
  font-variant-ligatures: character-variant;
  font-size: 100px;
  color: #000000;
  -moz-font-feature-settings: 'cv83' 2, 'hlig';
  -webkit-font-feature-settings: 'cv83' 2, 'hlig';
  -ms-font-feature-settings: 'cv83' 2, 'hlig';
  font-feature-settings: 'cv83' 2, 'hlig';
}

<p><b>Class character-variant cv83 2 for q́ꝫ:</b>
<span class='character-variant83'></br>
<i> &#113;&#769;&#42859;</i></span></p>


![Screen Shot 2022-02-25 at 09 48 16](https://user-images.githubusercontent.com/18691188/155742933-27457678-5578-41b5-b96f-a5877cc4d64a.png)

As the accent goes in the middle, the transformation does not complete. If I only apply hlig + cv83 2 to qꝫ (without the accent, or moving the accent before q), I get this:
![Screen Shot 2022-02-25 at 09 58 12](https://user-images.githubusercontent.com/18691188/155743437-fa1ed655-2fa3-470c-b707-9b29312c5b32.png)
All the very best,
Daniel

**Comment by RolandDreger** [comment]
Hi Daniel,

i also get it only with the accent before the q and a negative kerning. 

<img width="1019" alt="Bildschirmfoto 2022-02-26 um 19 19 05" src="https://user-images.githubusercontent.com/19747449/155854872-90dad65f-1ff0-4c6b-9f48-c61f85eeae8a.png">

Maybe a problem with the programming of the font? Or InDesign can't handle it? But unfortunately I can't do anything with scripting in that case I think. I just apply the property with the script to the text.

Roland

**Comment by dhinostroza** [comment]
That was a great suggestion! I gave negative kerning to the accent and it looks great!
I'll look into the Spanish translation now and provide the files as soon as I have them ready.
All the very best,
Daniel

**Comment by dhinostroza** [comment]
[openTypeFeatures_es.jsx.zip](https://github.com/RolandDreger/open-type-features/files/8164055/openTypeFeatures_es.jsx.zip)
Hi, Roland:
I have attached the file with the Spanish translation, following the InDesign wording as closely as possible.
Feel free to contact me if you have any questions or remarks.
Very kind regards,
Daniel

**Comment by RolandDreger** [comment]
Thanks for the translations Daniel, that's awesome, I will add/merge them this weekend.

Best regards
Roland
